### ISSUE TITLE
[incompatibility] Jumping dots with module profile module

### ISSUE THREAD

**Issue by Orionox** [sanguaire/portrait-box#5]
For whatever reason this mod makes the dots in the module profile module jump while on the module management page.

**Comment by sanguaire** [comment]
Can you send a Screenshot of this behavior?

**Comment by Orionox** [comment]
![Screenshot 2023-03-04 211110](https://user-images.githubusercontent.com/20059838/222941241-a781acc4-8ce1-43c0-ba8a-316d25f25952.jpg)
so, it's sort of hard to screenshot since the issue is that there are twice as many green dots as normal, and the green dots are moving up and down repeatedly.

**Comment by sanguaire** [comment]
Can you try it with a world with no other modules? I can not replicate this issue.
Can you give me a snapshot of the html element  from the development tools?

**Comment by sanguaire** [comment]
From which module you get the green dots? I'm trying to simulate this behaviour.

**Comment by sanguaire** [comment]
No answer from [Orionox](https://github.com/Orionox) in 4 weeks, so I can not reproduce.

**Comment by Orionox** [comment]
sorry, I had an extended time spent away from my computer.  The modules that adds the green dots is module profiles

**Comment by sanguaire** [comment]
Sorry, but this is a problem with the bounce keyframe in "module profiles". They use the same name that is used in the animate.css library. I have no solution to for this problem.
Maybe the developer of "module profiles" can change the bounce keyframe name to a name that is more specific aka use a module prefix in the name, so that the keyframe name dosn't conflict with the animate.css library.

**Comment by sanguaire** [comment]
I have opened an issue in "Module Profile" https://github.com/NateHawk85/module-profiles/issues/27#issue-1677954243
