### ISSUE TITLE
Version 11

### ISSUE THREAD

**Issue by justinthejaguar** [sanguaire/portrait-box#7]
Hello. I really enjoy your module in my 5e and OSE games. I was wondering if you plan to make it compatible with version 11.

**Comment by sanguaire** [comment]
Next Version will be V11 compatible. I have to do more tests to release this version.

**Comment by zero127** [comment]
While we wait, changing the compatibility and locking it will let you keep using it for now (just don't forget to check back manually if you lock it to keep it from updating to v10 max compat; which is what i was doing here). 

I at least, haven't found anything that doesn't work, but I only use a default masked image with no effects on hover. But, on that note, hell of a wonderful module, it's a huge hit at our table. Really helps folks see the art on huge 50px/sq maps. It's greatly appreciated! Thanks for the update, whenever it's ready. So grateful that so many devs are so diligent at updating these.  It's been an eye-opening two weeks since i jumped to 11 too soon, and had to live life without all this QOL module makers have brought us. So seriously: thank you!

**Comment by sanguaire** [comment]
v0.4.8 should be compatible. Test and enjoy :)
